### ISSUE TITLE
Changes to .gitignore are only effective after restart

### ISSUE THREAD

**Issue by Boscop** [passcod/cargo-watch#104] opened 2018-11-23 11:18 UTC
Changes to .gitignore are only effective after restart, e.g. if I have `cargo watch -x run` running and then I add a file (that I'm going to create) to .gitignore, and then create the file, it will abort and retrigger `cargo run`, also for every time I save that file, even though it's now in .gitignore and should be ignored by cargo-watch. This means there is no way to create new files that should be ignored without interrupting the currently running process :/

I'd prefer if cargo-watch would reload the .gitignore file's contents when it changes so that the changes are effective from then on, without having to abort my currently running process & restart `cargo watch -x run`.

**Comment by passcod** [comment] 2020-06-06 02:13
Duplicate of #144

**Closed by passcod** 2020-06-06 02:13 UTC
Labels: enhancement, upstream
