### ISSUE TITLE
Different versions in docker vs host install

### ISSUE THREAD

**Issue by 1wilkens** [passcod/cargo-watch#90] opened 2018-03-24 10:57 UTC
For some reason I get a broken? version of `cargo-watch` inside my app's docker container. Both versions are reported as `6.0.0` but the help output is different.

In docker (rustlang/rust:nightly):
```sh
$ cargo-watch --version
cargo-watch 6.0.0
$ cargo-watch --help
cargo-watch 6.0.0

USAGE:
    cargo
    cargo <SUBCOMMAND>

FLAGS:
    -h, --help       
    -V, --version    

SUBCOMMANDS:
    watch    Watches over your Cargo project’s source
```
On my development machine:
```sh
$ cargo-watch --version
cargo-watch 6.0.0
$ cargo-watch --help
cargo-watch 6.0.0
https://github.com/passcod/cargo-watch
Watches over your Cargo project’s source

USAGE:
    cargo watch [FLAGS] [OPTIONS]

FLAGS:
    -c, --clear             Clear the screen before each run
        --debug             Show debug output
    -h, --help              Display this message
        --ignore-nothing    Ignore nothing, not even target/ and .git/
        --no-gitignore      Don’t use .gitignore files
        --no-restart        Don’t restart command while it’s still running
        --poll              Force use of polling for file changes
        --postpone          Postpone first run until a file changes
    -q, --quiet             Suppress output from cargo-watch itself
    -V, --version           Display version information

OPTIONS:
    -x, --exec <cmd>...          Cargo command(s) to execute on changes [default: check]
    -s, --shell <cmd>...         Shell command(s) to execute on changes
    -d, --delay <delay>          File updates debounce delay in seconds [default: 0.5]
    -i, --ignore <pattern>...    Ignore a glob/gitignore-style pattern
    -w, --watch <watch>...       Watch specific file(s) or folder(s) [default: .]

Cargo commands (-x) are always executed before shell commands (-s).

By default, your entire project is watched, except for the target/ and .git/ folders, and your .gitignore files are used to filter paths.
```

The docker version does behave like the help page suggests and does not accept flags like "-x".
In both cases the install was performed via `cargo install -f cargo-watch`  and I even tried `--all-features' for good measure. The only difference I can think is the toolchain version which seems to be older in docker than on my machine. I also completely recreated the container image and reinstalled `cargo-watch` on my dev machine but the difference persists.

**Comment by passcod** [comment] 2018-03-24 10:59
If you use cargo-watch standalone, you need to specify `watch` as the first parameter. That's what the first error is saying. So, actually, it's your dev machine version that's behaving wrong.

**Comment by passcod** [comment] 2018-03-24 11:01
Just in case, can you give the rustc and cargo versions in both?

**Comment by passcod** [comment] 2018-03-24 11:02
Oh and whether you're using rustup in either. I assume you are on your dev machine, but not in docker?

**Comment by passcod** [comment] 2018-03-24 11:27
In both cases, `cargo watch` (notice the space) should work fine.

**Comment by 1wilkens** [comment] 2018-03-24 11:31
Thanks for the quick response!
I did not know invocation makes a difference. I double checked and it seems that the docker version is still behaving wrong.

| Machine | command | output |
| -- | -- | -- |
| dev | cargo watch --help | long
| dev | cargo-watch --help | short
| dev | cargo-watch watch --help | long
| docker | cargo watch --help | short (!)
| docker | cargo-watch --help | short
| docker | cargo-watch watch --help | long (!)

So the long form `cargo-watch watch` always behaves correctly and only the subcommand form fails fails in docker. Both my dev machine and docker use rustup (see: https://hub.docker.com/r/rustlang/rust/~/dockerfile/).

Toolchain versions dev:
rustup 1.11.0
rustc 1.26.0-nightly (c08480fce 2018-03-23)
cargo 1.26.0-nightly (d10ec661b 2018-03-20)

Toolchain versions docker:
rustup 1.11.0 (e751ff9f8 2018-02-13)
rustc 1.26.0-nightly (75af15ee6 2018-03-20)
cargo 1.26.0-nightly (d6c3983fe 2018-03-16)

For now I can use the long form in docker but there seems to be an underlying issue.

**Comment by passcod** [comment] 2018-03-24 11:38
Wow, okay, that's really odd. I can't boot up the docker daemon right now, but I'll try to figure it out tomorrow. Thanks for the detailed testing!

**Comment by 1wilkens** [comment] 2018-03-24 11:39
No worries, I am happy I have a version that works for now ;)

**Comment by passcod** [comment] 2018-04-01 01:37
Well, I'm sorry for taking this long to test it... but I have an issue: I can't reproduce this :( I tried with both /bin/sh and /bin/bash, in case it was a weird shell issue (which was my first guess).

Could you try again with a fresh pull of the docker image? Perhaps it was an issue that went away in the last week...

**Comment by 1wilkens** [comment] 2018-04-03 13:26
Yeah sure I already thought it might be versions weirdness. I'll try later and report back.

**Comment by passcod** [comment] 2018-07-13 00:15
Closing (reopen if it happens again)

**Closed by passcod** 2018-07-13 00:15 UTC

**Comment by 1wilkens** [comment] 2018-07-13 09:17
Sorry I complete forgot this issue. I had no issues after new pulls, this can stay closed.
Thanks for you quick help!
