### ISSUE TITLE
permissions on ignored directory not permitting enumeration result in immediate exit

### ISSUE THREAD

**Issue by jmesmon** [passcod/cargo-watch#146] opened 2020-05-15 17:42 UTC
So this is a bunch of interacting issues, which may be related to `watchexec` more than `cargo-watch`, but I'm experiencing them using `cargo-watch` so I'm adding this here initially

  - subdirectories, even if they are (based on the ignore files/patterns) always going to have all their files ignored, have a inotify watch added and are enumerated.
  - when one of these subdirectories happens to have permissions that forbid enumeration for the user running cargo-watch, a very terse error message is emitted and `cargo-watch` exits:

```
Error: I/O error: Permission denied (os error 13)
```

  - `strace -ff` can be used to track down the offending file.

This could probably be fixed/improved in a few ways:

1. warn, but don't exit on permissions issues when enumerating files
2. emit a file path
3. avoid enumerating into ignored directories that lack ignore

**Comment by passcod** [comment] 2020-05-16 00:05
Dupe of #135 I think

**Comment by passcod** [comment] 2020-05-16 00:06
Except this part, which is interesting:

> subdirectories, even if they are (based on the ignore files/patterns) always going to have all their files ignored, have a inotify watch added and are enumerated.

**Comment by jmesmon** [comment] 2020-05-20 23:48
Agreed, part is a dup of https://github.com/passcod/cargo-watch/issues/135.

On the "inotify watches happening even on ignored directories", I noticed this issue (with permissions) due to some build directories (generated by bazel and included in the ignores) lacking `x` permissions. 

I've looked a bit, and I think the core issue is that `watchexec` relies on `notify`'s recursive watch support, which doesn't consult the ignores and adds watches for all subdirectories (https://github.com/watchexec/watchexec/blob/f8f6c0ac5ab184e9153e8118635de758cbdae704/src/watcher.rs#L35, https://github.com/notify-rs/notify/blob/eed64ac9088ec1aab5c4710ef7232f0fbee49e0a/src/inotify.rs#L411-L422 )

An option is likely just enumerating paths ourselves, applying ignores, and using non-recursive watch mechanisms, though this may not map well to other platforms (and there's also the caveat that there might be directories that don't yet exist but would be exempt from the ignores, requiring the registration of an inotify watch on their ignored parent directory)

**Comment by passcod** [comment] 2020-05-20 23:52
Yeah, let's not. Having been notify's maintainer, that sounds like hell. We can filter better instead, for some loss in efficiency (watching too much) which we're already incurring tbh.

**Comment by passcod** [comment] 2021-04-11 11:11
Closing in favour of upstream issue: https://github.com/watchexec/watchexec/issues/149.

**Closed by passcod** 2021-04-11 11:11 UTC
Labels: enhancement, help wanted, upstream
