### ISSUE TITLE
Use Space to re-run manually

### ISSUE THREAD

**Issue by BourgondAries** [passcod/cargo-watch#130] opened 2019-09-17 07:14 UTC
`entr` is a similar watcher that allows the user to press the spacebar and re-run whatever command it was given. I think this would be useful for cargo-watch as well.

In some cases I edit, cargo-watch tests, but sometimes a test seems non-deterministic, so I just want to be able to press space a couple of times instead of saving a file.

**Comment by passcod** [comment] 2019-09-17 12:02
Duplicate of #123

**Closed by passcod** 2019-09-17 12:02 UTC
