### ISSUE TITLE
Watch does not ignore .git/info/exclude

### ISSUE THREAD

**Issue by blargg** [passcod/cargo-watch#164] opened 2021-02-02 05:47 UTC
When using git's ignore files, we do not use `.git/info/exclude`. This is basically a local only `.gitignore` that you don't commit along with the code.

This can be a bit confusing, as git will ignore those files, but `cargo watch` will not.

**Comment by passcod** [comment] 2021-02-02 08:34
Duplicate of #142

**Closed by passcod** 2021-02-02 08:34 UTC
